### ISSUE TITLE
Dependency on org.codehaus.woodstox:stax2-api:3.1.1 causes failures

### ISSUE THREAD

**Issue by jameswennmacher** [FasterXML/StaxMate#9]
Suggest updating the dependency of org.codehaus.woodstox:stax2-api to minimum 3.1.4.

Background:
Our project used to depend upon org.codehaus.staxmate:staxmate:2.0.1.  That 2.0.1 version had a dependency on org.codehaus.woodstox:stax2-api of [3.0.4, 3.5.0) which allowed uPortal to pick up org.codehaus.woodstox:stax2-api:3.1.4.  In updating to com.fasterxml.staxmate:staxmate:2.2.1, it requires org.codehaus.woodstox:stax2-api:3.1.1 which caused failures (see 2nd comment on https://issues.jasig.org/browse/UP-4455).  I looked into it enough to recognize that the license header at the top of our files (see https://github.com/Jasig/uPortal/blob/uportal-4.2.0/uportal-war/src/test/java/org/jasig/portal/io/xml/subscribedfragment/SubscribedFragmentDataUpgradeTest.java for example) causes the failure.  Using org.codehaus.woodstox:stax2-api:3.1.4 fixes this issue.

I suggest you depend on v3.1.4 rather than v3.1.1 to avoid this issue for others.  Thanks.

**Comment by cowtowncoder** [comment]
I will release 2.3.0 now, as I also upgraded Woodstox dependency to 4.4. This should not matter a lot since interface for Woodstox 4.x hasn't changed in incompatible way, nor does StaxMate 2.3 make any use of new functionality. But given that Woodstox 5 is the next big upgrade, no point in using an older version.

Thank you for pointing out the issue, let me know if you find other problems.
